### ISSUE TITLE
After a while the app reports Error 

### ISSUE THREAD

**Issue by mhoogenbosch** [rogierhofboer/com.ikea.tradfri.gateway#29]
Sometimes the communication with the hub stops. It only reports an error when trying to turn on / off the lights.

At that time the 'normal' ikea app still works and can turn on and off the lights. When i restart the app from homey it starts working again. 

Is there a way to troubleshoot? It is not a wifi problem because the normal app still works and I only need to reboot the ikea app. 

Currently working around it by rebooting the app every hour.

**Comment by PascalBu** [comment]
Same here, Homey app is randomly crashing while IKEA app etc keeps working...

**Comment by mhoogenbosch** [comment]
![IMG_3045](https://user-images.githubusercontent.com/36899598/57041365-50d14e80-6c62-11e9-9ea8-eae3e38c353a.PNG)


After rebooting the app, it starts working again.

**Comment by jpligthart** [comment]
Same issue here!
Is quite annoying so would be great if this could be fixed!
For me restart did not work... So I have even a bigger problem!

**Comment by martijnvg30** [comment]
Same issue here, sadly a reboot did not fix it.

**Comment by PascalBu** [comment]
Update from own experience: a reset of the Tradfri hub itself fixed my issues! Stupid that I did not think of this before... 😴

**Comment by martijnvg30** [comment]
That is what works for me as well. But then after a reboot of the tradfri gateway I need to re- authenticate the homey app. If this could be fixed, that would be awesome, and if we can contribute in any way then please let me know.

**Comment by json81** [comment]
Fixed in v0.1.2 and should be closed.

**Comment by esp0** [comment]
This still happens in v0.1.2. Are there any logs somewhere that I can look at/send somewhere?

**Comment by rogierhofboer** [comment]
I see it happen and get crash reports, but no-one really reported it directly to me.
It seems to happen inside node-tradfri-client:

```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: unexpected response (4.00) to observeDevice(65568): [object Object]
    at TradfriClient.handleNonSuccessfulResponse (/node_modules/node-tradfri-client/build/tradfri-client.js:750:32)
    at TradfriClient.observeDevice_callback (/node_modules/node-tradfri-client/build/tradfri-client.js:389:23)
    at PendingRequest.handleResponse [as callback] (/node_modules/node-tradfri-client/build/tradfri-client.js:346:41)
    at Function.onMessage (/node_modules/node-coap-client/build/CoapClient.js:631:33)
    at SocketWrapper.emit (events.js:311:20)
    at Socket.<anonymous> (/node_modules/node-coap-client/build/lib/SocketWrapper.js:12:18)
    at Socket.emit (events.js:311:20)
    at Socket.udp_onMessage (/node_modules/node-dtls-client/build/dtls.js:189:34)
    at Socket.emit (events.js:311:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
Emitted 'error' event on TradfriClient instance at:
    at TradfriClient.handleNonSuccessfulResponse (/node_modules/node-tradfri-client/build/tradfri-client.js:750:18)
    at TradfriClient.observeDevice_callback (/node_modules/node-tradfri-client/build/tradfri-client.js:389:23)
    [... lines matching original stack trace ...]
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
```

**Comment by rogierhofboer** [comment]
I still get many reports of crashes in the (external) node-tradfri-client. The stack trace is always the one above.
Because I don't experience the problem and cannot reproduce it, please contact me (via this issue or via email) so we can look at it.
